// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package controller

type Node interface {
	IsNode()
}

type Instruction struct {
	ID     string  `json:"id"`
	Price  *int    `json:"price"`
	Target *string `json:"target"`
}

type Item struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	Price      int         `json:"price"`
	ItemHolder *ItemHolder `json:"itemHolder"`
}

type ItemHolder struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Nickname  *string `json:"nickname"`
	HoldItems []Item  `json:"holdItems"`
}

type ItemHolderInput struct {
	Name     string  `json:"name"`
	Nickname *string `json:"nickname"`
}

type ItemInput struct {
	Name         string `json:"name"`
	Price        int    `json:"price"`
	ItemHolderID string `json:"itemHolderId"`
}

type NewInstruction struct {
	Price  *int    `json:"price"`
	Target *string `json:"target"`
}

type NewOrder struct {
	Name         string           `json:"name"`
	User         *NewUser         `json:"user"`
	OrderDetails []NewOrderDetail `json:"orderDetails"`
}

type NewOrderDetail struct {
	Order       *NewOrder       `json:"order"`
	Instruction *NewInstruction `json:"instruction"`
}

type NewOrganization struct {
	Name                string  `json:"name"`
	UpperOrganizationID *string `json:"upperOrganizationId"`
}

type NewUser struct {
	Name          string             `json:"name"`
	Organizations []*NewOrganization `json:"organizations"`
}

type NoopInput struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type NoopPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type Order struct {
	ID           string        `json:"id"`
	Name         string        `json:"name"`
	User         *User         `json:"user"`
	OrderDetails []OrderDetail `json:"orderDetails"`
}

type OrderDetail struct {
	ID          string       `json:"id"`
	Order       *Order       `json:"order"`
	Instruction *Instruction `json:"instruction"`
}

type Organization struct {
	ID                  string  `json:"id"`
	Name                string  `json:"name"`
	UpperOrganizationID *string `json:"upperOrganizationId"`
	Users               []*User `json:"users"`
}

type User struct {
	ID            string          `json:"id"`
	Name          string          `json:"name"`
	Organizations []*Organization `json:"organizations"`
}
