// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package controller

type Node interface {
	IsNode()
}

type Item struct {
	ID         string      `json:"id"`
	Name       string      `json:"name"`
	Price      int         `json:"price"`
	ItemHolder *ItemHolder `json:"itemHolder"`
}

type ItemHolder struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Nickname  *string `json:"nickname"`
	HoldItems []Item  `json:"holdItems"`
}

type ItemHolderInput struct {
	Name     string  `json:"name"`
	Nickname *string `json:"nickname"`
}

type ItemInput struct {
	Name         string `json:"name"`
	Price        int    `json:"price"`
	ItemHolderID string `json:"itemHolderId"`
}

type NoopInput struct {
	ClientMutationID *string `json:"clientMutationId"`
}

type NoopPayload struct {
	ClientMutationID *string `json:"clientMutationId"`
}
