// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/sky0621/fiktivt-handelssystem/adapter/controller"
	"github.com/sky0621/fiktivt-handelssystem/adapter/gateway"
	"github.com/sky0621/fiktivt-handelssystem/config"
	"github.com/sky0621/fiktivt-handelssystem/driver"
	"github.com/sky0621/fiktivt-handelssystem/system"
	"github.com/sky0621/fiktivt-handelssystem/usecase"
)

// Injectors from wire.go:

func di(cfg config.Config) App {
	rdb := driver.NewRDB(cfg)
	appLogger := system.NewAppLogger()
	item := gateway.NewItem(rdb, appLogger)
	usecaseItem := usecase.NewItem(item)
	itemHolder := gateway.NewItemHolder(rdb, appLogger)
	usecaseItemHolder := usecase.NewItemHolder(itemHolder)
	resolverRoot := controller.NewResolverRoot(usecaseItem, usecaseItemHolder, appLogger)
	web := driver.NewWeb(cfg, resolverRoot, appLogger)
	app := NewApp(cfg, rdb, web)
	return app
}

// wire.go:

var superSet = wire.NewSet(system.NewAppLogger, driver.NewRDB, gateway.NewItem, gateway.NewItemHolder, usecase.NewItem, usecase.NewItemHolder, controller.NewResolverRoot, driver.NewWeb, NewApp)
