// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/sky0621/fiktivt-handelssystem/config"
	"github.com/sky0621/fiktivt-handelssystem/driver"
)

// Injectors from wire.go:

func Initialize(cfg config.Config) App {
	rdb := driver.NewRDB(cfg)
	web := driver.NewWeb(cfg)
	app := NewApp(cfg, rdb, web)
	return app
}

// wire.go:

var superSet = wire.NewSet(driver.NewRDB, driver.NewWeb, NewApp)
